[AIT-006] .github ,workflows and playwright test yaml updated

diff --git a/.github/workflows/playwright-tests.yml b/.github/workflows/playwright-tests.yml
--- a/.github/workflows/playwright-tests.yml
+++ b/.github/workflows/playwright-tests.yml
@@ -28,16 +28,16 @@ jobs:
       - name: Install dependencies
         run: npm install --unsafe-perm=true --allow-root
 
-      # Install Playwright directly through npm instead of npx
-      - name: Install Playwright Browsers
+      # Install Playwright and Browsers
+      - name: Install Playwright and Browsers
         run: |
-          npm install playwright
+          npm install playwright --save-dev
           npx playwright install
 
       - name: Run Playwright tests
         run: |
-          CI=true npx playwright test --reporter=html,allure-playwright || echo "Tests failed, review logs."
-          
+          CI=true ./node_modules/.bin/playwright test --reporter=html || echo "Tests failed, review logs."
+
           # Always check if the report directory exists
           if [ -d playwright-report ]; then
             echo "artifact_exists=true" >> $GITHUB_ENV
@@ -59,16 +59,9 @@ jobs:
           name: AIT-Playwright-HTML-Report
           path: playwright-report/
 
-      - name: Upload Allure Results
-        if: env.artifact_exists == 'true'
-        uses: actions/upload-artifact@v4
-        with:
-          name: AIT-Playwright-Allure-Results
-          path: test-results/allure-results/
-
       - name: Run Accessibility Tests
         run: |
-          CI=true npx playwright test --reporter=html,allure-playwright --project=Chromium --grep "Accessibility Testing Suite" || echo "Accessibility tests failed, review logs."
+          CI=true ./node_modules/.bin/playwright test --reporter=html --grep "Accessibility Testing Suite" || echo "Accessibility tests failed, review logs."
 
           # Always check if the report directory exists for accessibility tests
           if [ -d accessibility-reports ]; then
